export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const SET_CURRENTVIEW = "SET_CURRENTVIEW";
export const SET_CURRENTVIEW_SINGLE = "SET_CURRENTVIEW_SINGLE";
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const UPLOAD_VIEW = "UPLOAD_VIEW";
